services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 youtube_downloader.asgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: celery -A youtube_downloader worker --loglevel=INFO -E --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    restart: always
    image: redis:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
