services:
  web:
    build: .
    command: daphne -u /tmp/daphne.sock youtube_downloader.asgi:application
    volumes:
      - .:/app
      - daphne-socket:/tmp  # Shared volume for the Unix socket
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: celery -A youtube_downloader worker --loglevel=INFO -E --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  flower:
    build: .
    command: celery -A youtube_downloader flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    env_file:
      - .env

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    restart: always
    image: redis:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs:/etc/ssl/certs  # Mount SSL certs directory
      - /etc/ssl/private:/etc/ssl/private  # Mount SSL private keys directory
      - daphne-socket:/tmp  # Shared volume for the Unix socket
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS port
    depends_on:
      - web

volumes:
  postgres_data:
  daphne-socket:  # Define a shared volume for the Unix socket
