version: '3'

services:
  web:
    build: .
    command: uvicorn youtube_downloader.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: celery -A youtube_downloader.celery worker --loglevel=INFO -E --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  flower:
    image: mher/flower
    command: celery -A youtube_downloader.celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - worker
      - redis
    env_file:
      - .env

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    restart: always
    image: redis:latest

volumes:
  postgres_data:
