# Generated by Django 5.1 on 2024-08-26 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('resolution', models.CharField(max_length=10)),
                ('include_audio', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=50)),
                ('progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='downloads/')),
            ],
        ),
    ]
