# Generated by Django 5.1 on 2024-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='resolution',
            field=models.CharField(max_length=18),
        ),
    ]
