# Generated by Django 5.1 on 2024-08-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_alter_downloadtask_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
