# Generated by Django 5.1 on 2024-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_downloadtask_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('fetching_metadata', 'Fetching Metadata'), ('downloading_video', 'Downloading Video'), ('downloading_audio', 'Downloading Audio'), ('merging', 'Merging Video and Audio'), ('uploading', 'Uploading to Storage'), ('completed', 'Completed'), ('error', 'Error')], default='queued', max_length=50),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
